#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    Host=`ifconfig en0|grep inet|grep -v inet6|awk '{print $2}'`        
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    Host=`ifconfig eth0|grep inet|grep -v inet6|awk '{print $2}'|tr -d 'addr:'`
elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
    # Do something under Windows NT platform
    echo "UNKNOW SYSTEM"
fi

consul agent -advertise ${Host} -client ${Host} -ui -data-dir ./config -server -datacenter dc1 -bootstrap >> /dev/null &
