// Code generated by protoc-gen-go.
// source: client.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	client.proto
	rpc.proto

It has these top-level messages:
	RegCaptchaC2S
	RegCaptchaS2C
	RegisterC2S
	RegisterS2C
	PasswordCaptchaC2S
	PasswordCaptchaS2C
	ChangePasswordC2S
	ChangePasswordS2C
	LoginC2S
	LoginS2C
	UserInfoModifyC2S
	UserInfoModifyS2C
	UserInfoGetC2S
	UserInfoGetS2C
	GeoUploadC2S
	CommonS2C
	RecentContactGetC2S
	RecentContactGetS2C
	Friend
	AuthC2S
	GetSessionC2S
	GetSessionS2C
	GetCaptchaC2S
	GetCaptchaS2C
	CheckCaptchaC2S
	CheckCaptchaS2C
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RegCaptchaC2S struct {
	PhoneNumber uint64 `protobuf:"varint,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
}

func (m *RegCaptchaC2S) Reset()                    { *m = RegCaptchaC2S{} }
func (m *RegCaptchaC2S) String() string            { return proto1.CompactTextString(m) }
func (*RegCaptchaC2S) ProtoMessage()               {}
func (*RegCaptchaC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RegCaptchaS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	Captcha uint32 `protobuf:"varint,2,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *RegCaptchaS2C) Reset()                    { *m = RegCaptchaS2C{} }
func (m *RegCaptchaS2C) String() string            { return proto1.CompactTextString(m) }
func (*RegCaptchaS2C) ProtoMessage()               {}
func (*RegCaptchaS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RegisterC2S struct {
	PhoneNumber uint64 `protobuf:"varint,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Captcha     uint32 `protobuf:"varint,3,opt,name=captcha" json:"captcha,omitempty"`
	Sex         uint32 `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
}

func (m *RegisterC2S) Reset()                    { *m = RegisterC2S{} }
func (m *RegisterC2S) String() string            { return proto1.CompactTextString(m) }
func (*RegisterC2S) ProtoMessage()               {}
func (*RegisterC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RegisterS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	UserID  uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	Session string `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
}

func (m *RegisterS2C) Reset()                    { *m = RegisterS2C{} }
func (m *RegisterS2C) String() string            { return proto1.CompactTextString(m) }
func (*RegisterS2C) ProtoMessage()               {}
func (*RegisterS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 修改密码
type PasswordCaptchaC2S struct {
	PhoneNumber uint64 `protobuf:"varint,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
}

func (m *PasswordCaptchaC2S) Reset()                    { *m = PasswordCaptchaC2S{} }
func (m *PasswordCaptchaC2S) String() string            { return proto1.CompactTextString(m) }
func (*PasswordCaptchaC2S) ProtoMessage()               {}
func (*PasswordCaptchaC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PasswordCaptchaS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	Captcha uint32 `protobuf:"varint,2,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *PasswordCaptchaS2C) Reset()                    { *m = PasswordCaptchaS2C{} }
func (m *PasswordCaptchaS2C) String() string            { return proto1.CompactTextString(m) }
func (*PasswordCaptchaS2C) ProtoMessage()               {}
func (*PasswordCaptchaS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ChangePasswordC2S struct {
	PhoneNumber uint64 `protobuf:"varint,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Captcha     uint32 `protobuf:"varint,3,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *ChangePasswordC2S) Reset()                    { *m = ChangePasswordC2S{} }
func (m *ChangePasswordC2S) String() string            { return proto1.CompactTextString(m) }
func (*ChangePasswordC2S) ProtoMessage()               {}
func (*ChangePasswordC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ChangePasswordS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *ChangePasswordS2C) Reset()                    { *m = ChangePasswordS2C{} }
func (m *ChangePasswordS2C) String() string            { return proto1.CompactTextString(m) }
func (*ChangePasswordS2C) ProtoMessage()               {}
func (*ChangePasswordS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type LoginC2S struct {
	PhoneNumber uint64 `protobuf:"varint,1,opt,name=phoneNumber" json:"phoneNumber,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginC2S) Reset()                    { *m = LoginC2S{} }
func (m *LoginC2S) String() string            { return proto1.CompactTextString(m) }
func (*LoginC2S) ProtoMessage()               {}
func (*LoginC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type LoginS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	UserID  uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	Session string `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
}

func (m *LoginS2C) Reset()                    { *m = LoginS2C{} }
func (m *LoginS2C) String() string            { return proto1.CompactTextString(m) }
func (*LoginS2C) ProtoMessage()               {}
func (*LoginS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// 用户信息修改
type UserInfoModifyC2S struct {
	UserID    uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Nickname  string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
	City      string `protobuf:"bytes,4,opt,name=city" json:"city,omitempty"`
}

func (m *UserInfoModifyC2S) Reset()                    { *m = UserInfoModifyC2S{} }
func (m *UserInfoModifyC2S) String() string            { return proto1.CompactTextString(m) }
func (*UserInfoModifyC2S) ProtoMessage()               {}
func (*UserInfoModifyC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type UserInfoModifyS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *UserInfoModifyS2C) Reset()                    { *m = UserInfoModifyS2C{} }
func (m *UserInfoModifyS2C) String() string            { return proto1.CompactTextString(m) }
func (*UserInfoModifyS2C) ProtoMessage()               {}
func (*UserInfoModifyS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type UserInfoGetC2S struct {
	TargetUserID uint64 `protobuf:"varint,1,opt,name=target_userID,json=targetUserID" json:"target_userID,omitempty"`
}

func (m *UserInfoGetC2S) Reset()                    { *m = UserInfoGetC2S{} }
func (m *UserInfoGetC2S) String() string            { return proto1.CompactTextString(m) }
func (*UserInfoGetC2S) ProtoMessage()               {}
func (*UserInfoGetC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type UserInfoGetS2C struct {
	ErrCode   uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	UserID    uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	Nickname  string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Signature string `protobuf:"bytes,4,opt,name=signature" json:"signature,omitempty"`
	City      string `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
	Sex       uint32 `protobuf:"varint,6,opt,name=sex" json:"sex,omitempty"`
}

func (m *UserInfoGetS2C) Reset()                    { *m = UserInfoGetS2C{} }
func (m *UserInfoGetS2C) String() string            { return proto1.CompactTextString(m) }
func (*UserInfoGetS2C) ProtoMessage()               {}
func (*UserInfoGetS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

// 用户关系相关
type GeoUploadC2S struct {
	UserID    uint64  `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
}

func (m *GeoUploadC2S) Reset()                    { *m = GeoUploadC2S{} }
func (m *GeoUploadC2S) String() string            { return proto1.CompactTextString(m) }
func (*GeoUploadC2S) ProtoMessage()               {}
func (*GeoUploadC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type CommonS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *CommonS2C) Reset()                    { *m = CommonS2C{} }
func (m *CommonS2C) String() string            { return proto1.CompactTextString(m) }
func (*CommonS2C) ProtoMessage()               {}
func (*CommonS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type RecentContactGetC2S struct {
	UserID uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *RecentContactGetC2S) Reset()                    { *m = RecentContactGetC2S{} }
func (m *RecentContactGetC2S) String() string            { return proto1.CompactTextString(m) }
func (*RecentContactGetC2S) ProtoMessage()               {}
func (*RecentContactGetC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type RecentContactGetS2C struct {
	ErrCode uint32    `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	Friends []*Friend `protobuf:"bytes,2,rep,name=friends" json:"friends,omitempty"`
}

func (m *RecentContactGetS2C) Reset()                    { *m = RecentContactGetS2C{} }
func (m *RecentContactGetS2C) String() string            { return proto1.CompactTextString(m) }
func (*RecentContactGetS2C) ProtoMessage()               {}
func (*RecentContactGetS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *RecentContactGetS2C) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

type Friend struct {
	UserID    uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
}

func (m *Friend) Reset()                    { *m = Friend{} }
func (m *Friend) String() string            { return proto1.CompactTextString(m) }
func (*Friend) ProtoMessage()               {}
func (*Friend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type AuthC2S struct {
	UserID  uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Session string `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
}

func (m *AuthC2S) Reset()                    { *m = AuthC2S{} }
func (m *AuthC2S) String() string            { return proto1.CompactTextString(m) }
func (*AuthC2S) ProtoMessage()               {}
func (*AuthC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type GetSessionC2S struct {
	UserID uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
}

func (m *GetSessionC2S) Reset()                    { *m = GetSessionC2S{} }
func (m *GetSessionC2S) String() string            { return proto1.CompactTextString(m) }
func (*GetSessionC2S) ProtoMessage()               {}
func (*GetSessionC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type GetSessionS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	UserID  uint64 `protobuf:"varint,2,opt,name=userID" json:"userID,omitempty"`
	Session string `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
}

func (m *GetSessionS2C) Reset()                    { *m = GetSessionS2C{} }
func (m *GetSessionS2C) String() string            { return proto1.CompactTextString(m) }
func (*GetSessionS2C) ProtoMessage()               {}
func (*GetSessionS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type GetCaptchaC2S struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *GetCaptchaC2S) Reset()                    { *m = GetCaptchaC2S{} }
func (m *GetCaptchaC2S) String() string            { return proto1.CompactTextString(m) }
func (*GetCaptchaC2S) ProtoMessage()               {}
func (*GetCaptchaC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type GetCaptchaS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
	Captcha uint32 `protobuf:"varint,2,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *GetCaptchaS2C) Reset()                    { *m = GetCaptchaS2C{} }
func (m *GetCaptchaS2C) String() string            { return proto1.CompactTextString(m) }
func (*GetCaptchaS2C) ProtoMessage()               {}
func (*GetCaptchaS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type CheckCaptchaC2S struct {
	Type    string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Captcha uint32 `protobuf:"varint,3,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *CheckCaptchaC2S) Reset()                    { *m = CheckCaptchaC2S{} }
func (m *CheckCaptchaC2S) String() string            { return proto1.CompactTextString(m) }
func (*CheckCaptchaC2S) ProtoMessage()               {}
func (*CheckCaptchaC2S) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type CheckCaptchaS2C struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=errCode" json:"errCode,omitempty"`
}

func (m *CheckCaptchaS2C) Reset()                    { *m = CheckCaptchaS2C{} }
func (m *CheckCaptchaS2C) String() string            { return proto1.CompactTextString(m) }
func (*CheckCaptchaS2C) ProtoMessage()               {}
func (*CheckCaptchaS2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func init() {
	proto1.RegisterType((*RegCaptchaC2S)(nil), "proto.RegCaptchaC2S")
	proto1.RegisterType((*RegCaptchaS2C)(nil), "proto.RegCaptchaS2C")
	proto1.RegisterType((*RegisterC2S)(nil), "proto.RegisterC2S")
	proto1.RegisterType((*RegisterS2C)(nil), "proto.RegisterS2C")
	proto1.RegisterType((*PasswordCaptchaC2S)(nil), "proto.PasswordCaptchaC2S")
	proto1.RegisterType((*PasswordCaptchaS2C)(nil), "proto.PasswordCaptchaS2C")
	proto1.RegisterType((*ChangePasswordC2S)(nil), "proto.ChangePasswordC2S")
	proto1.RegisterType((*ChangePasswordS2C)(nil), "proto.ChangePasswordS2C")
	proto1.RegisterType((*LoginC2S)(nil), "proto.LoginC2S")
	proto1.RegisterType((*LoginS2C)(nil), "proto.LoginS2C")
	proto1.RegisterType((*UserInfoModifyC2S)(nil), "proto.UserInfoModifyC2S")
	proto1.RegisterType((*UserInfoModifyS2C)(nil), "proto.UserInfoModifyS2C")
	proto1.RegisterType((*UserInfoGetC2S)(nil), "proto.UserInfoGetC2S")
	proto1.RegisterType((*UserInfoGetS2C)(nil), "proto.UserInfoGetS2C")
	proto1.RegisterType((*GeoUploadC2S)(nil), "proto.GeoUploadC2S")
	proto1.RegisterType((*CommonS2C)(nil), "proto.CommonS2C")
	proto1.RegisterType((*RecentContactGetC2S)(nil), "proto.RecentContactGetC2S")
	proto1.RegisterType((*RecentContactGetS2C)(nil), "proto.RecentContactGetS2C")
	proto1.RegisterType((*Friend)(nil), "proto.Friend")
	proto1.RegisterType((*AuthC2S)(nil), "proto.AuthC2S")
	proto1.RegisterType((*GetSessionC2S)(nil), "proto.GetSessionC2S")
	proto1.RegisterType((*GetSessionS2C)(nil), "proto.GetSessionS2C")
	proto1.RegisterType((*GetCaptchaC2S)(nil), "proto.GetCaptchaC2S")
	proto1.RegisterType((*GetCaptchaS2C)(nil), "proto.GetCaptchaS2C")
	proto1.RegisterType((*CheckCaptchaC2S)(nil), "proto.CheckCaptchaC2S")
	proto1.RegisterType((*CheckCaptchaS2C)(nil), "proto.CheckCaptchaS2C")
}

func init() { proto1.RegisterFile("client.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0xdf, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0x7f, 0xac, 0x5d, 0xaf, 0x2d, 0xb0, 0x20, 0xa1, 0x0a, 0xf1, 0x30, 0x19, 0xa1, 0x4d,
	0x42, 0x4c, 0xa2, 0x68, 0xbc, 0x20, 0x21, 0xa1, 0x4c, 0x0c, 0x24, 0x40, 0xe0, 0x69, 0x08, 0xc4,
	0x03, 0x78, 0x89, 0x9b, 0x46, 0x6d, 0xed, 0xc8, 0x76, 0x34, 0xf2, 0xef, 0xf0, 0x97, 0x62, 0x3b,
	0x49, 0x93, 0x6c, 0x9a, 0xc5, 0xca, 0xf6, 0x14, 0xdf, 0xf9, 0x7c, 0xdf, 0x77, 0x9f, 0xcf, 0x17,
	0x18, 0x05, 0xcb, 0x98, 0x32, 0x75, 0x90, 0x08, 0xae, 0xb8, 0xb7, 0x65, 0x3f, 0xe8, 0x39, 0x8c,
	0x31, 0x8d, 0x7c, 0x92, 0xa8, 0x60, 0x4e, 0xfc, 0xe9, 0x89, 0xb7, 0x0b, 0xc3, 0x64, 0xce, 0x19,
	0xfd, 0x94, 0xae, 0xce, 0xa8, 0x98, 0xb4, 0x76, 0x5b, 0xfb, 0x5d, 0x5c, 0x77, 0x21, 0xbf, 0x7e,
	0xe4, 0x64, 0xea, 0x7b, 0x13, 0xe8, 0x53, 0x21, 0x7c, 0x1e, 0x52, 0x1b, 0x3e, 0xc6, 0xa5, 0x69,
	0x76, 0x82, 0x3c, 0x6e, 0xd2, 0xce, 0x77, 0x0a, 0x13, 0x9d, 0xc3, 0x50, 0x27, 0x89, 0xa5, 0xa2,
	0xe2, 0x9f, 0x50, 0xbd, 0x87, 0xb0, 0x9d, 0x10, 0x29, 0xcf, 0xb9, 0x08, 0x6d, 0xae, 0x01, 0x5e,
	0xdb, 0x75, 0x98, 0x4e, 0x03, 0xc6, 0xbb, 0x07, 0x1d, 0x49, 0x7f, 0x4f, 0xba, 0xd6, 0x6b, 0x96,
	0xe8, 0x7b, 0x05, 0xec, 0xe6, 0xfe, 0x00, 0x7a, 0xa9, 0xa4, 0xe2, 0xfd, 0x91, 0x85, 0xeb, 0xe2,
	0xc2, 0x32, 0x27, 0x24, 0x95, 0x32, 0xe6, 0xcc, 0x82, 0x0d, 0x70, 0x69, 0xa2, 0x97, 0xe0, 0x7d,
	0x2e, 0x28, 0x5d, 0x4b, 0xd0, 0x77, 0x97, 0xce, 0x6d, 0xaa, 0xea, 0x02, 0x76, 0xfc, 0x39, 0x61,
	0x11, 0x5d, 0xe7, 0xbb, 0x3d, 0x6d, 0xd1, 0xb3, 0x8b, 0x60, 0x4e, 0xd6, 0xba, 0xca, 0xed, 0x0f,
	0x3c, 0x8a, 0xd9, 0x7f, 0x53, 0x42, 0x5f, 0x8b, 0x4c, 0x37, 0x7d, 0x7f, 0x19, 0xec, 0x9c, 0x9a,
	0x18, 0x36, 0xe3, 0x1f, 0x79, 0x18, 0xcf, 0x32, 0x43, 0xb5, 0x4a, 0xd3, 0x6a, 0xa4, 0xd1, 0x04,
	0x59, 0x1c, 0x2c, 0x18, 0x59, 0xd1, 0x92, 0x60, 0x69, 0x7b, 0x8f, 0x60, 0x20, 0xe3, 0x88, 0x11,
	0x95, 0x0a, 0x5a, 0x80, 0x54, 0x0e, 0xcf, 0x83, 0x6e, 0x10, 0xab, 0xcc, 0x36, 0xe5, 0x00, 0xdb,
	0xb5, 0xd1, 0xb2, 0x09, 0xed, 0xd6, 0xf2, 0x10, 0xee, 0x94, 0xe1, 0xc7, 0x54, 0x19, 0x9a, 0x8f,
	0x61, 0xac, 0x88, 0x88, 0xa8, 0xfa, 0xd9, 0x60, 0x3b, 0xca, 0x9d, 0x36, 0xf8, 0x08, 0xfd, 0x69,
	0x35, 0xce, 0x6d, 0xa6, 0x5f, 0xbd, 0xf0, 0x8e, 0xab, 0xf0, 0xee, 0x55, 0x85, 0x6f, 0x55, 0x85,
	0x97, 0x0f, 0xb4, 0x57, 0x3d, 0xd0, 0x5f, 0x30, 0x3a, 0xa6, 0xfc, 0x34, 0x59, 0x72, 0x12, 0xba,
	0x2e, 0x40, 0x63, 0x2d, 0x39, 0x8b, 0x62, 0x95, 0x86, 0xf9, 0x0d, 0xb4, 0x70, 0xe5, 0x30, 0x2c,
	0x97, 0x44, 0xe5, 0x9b, 0x1d, 0xbb, 0xb9, 0xb6, 0xd1, 0x13, 0x18, 0xf8, 0x7c, 0xb5, 0xe2, 0xee,
	0x06, 0xd2, 0x77, 0x72, 0x1f, 0xd3, 0x40, 0x4f, 0x4c, 0x9f, 0x33, 0x45, 0x02, 0x55, 0x28, 0x7d,
	0x05, 0x1f, 0xf4, 0xed, 0x72, 0xb8, 0x5b, 0xe0, 0x3d, 0xe8, 0xcf, 0x84, 0x9e, 0xc8, 0xa1, 0xd4,
	0xf4, 0x3b, 0xfb, 0xc3, 0xe9, 0x38, 0x1f, 0xcd, 0x07, 0x6f, 0xad, 0x17, 0x97, 0xbb, 0xe8, 0x35,
	0xf4, 0x72, 0x97, 0x4b, 0x8b, 0x4a, 0xf7, 0xf6, 0x05, 0xdd, 0xd1, 0x2b, 0xe8, 0xbf, 0x49, 0xd5,
	0xdc, 0x25, 0x66, 0xed, 0x51, 0xb4, 0x9b, 0x8f, 0x62, 0x0f, 0xc6, 0xa6, 0x92, 0xdc, 0x72, 0xd5,
	0xff, 0xa3, 0x1e, 0x78, 0xd3, 0x4f, 0xf3, 0xd0, 0x26, 0xaf, 0x4d, 0x55, 0xdd, 0x4b, 0x2a, 0x4b,
	0xf2, 0xcc, 0xba, 0x97, 0xcc, 0xda, 0xf4, 0xd2, 0x82, 0x66, 0x45, 0x01, 0x66, 0x69, 0x7e, 0x55,
	0xd5, 0xb1, 0x4d, 0x87, 0xea, 0x17, 0xb8, 0xeb, 0xcf, 0x69, 0xb0, 0xb8, 0x2e, 0xba, 0x63, 0x74,
	0x3e, 0x6d, 0xa6, 0x74, 0x32, 0x3b, 0xeb, 0xd9, 0xae, 0x78, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x94, 0x95, 0xcf, 0x11, 0xc0, 0x07, 0x00, 0x00,
}
