// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CaptchaManager service

type CaptchaManagerClient interface {
	GetCaptcha(ctx context.Context, in *GetCaptchaC2S, opts ...grpc.CallOption) (*GetCaptchaS2C, error)
	CheckCaptcha(ctx context.Context, in *CheckCaptchaC2S, opts ...grpc.CallOption) (*CheckCaptchaS2C, error)
}

type captchaManagerClient struct {
	cc *grpc.ClientConn
}

func NewCaptchaManagerClient(cc *grpc.ClientConn) CaptchaManagerClient {
	return &captchaManagerClient{cc}
}

func (c *captchaManagerClient) GetCaptcha(ctx context.Context, in *GetCaptchaC2S, opts ...grpc.CallOption) (*GetCaptchaS2C, error) {
	out := new(GetCaptchaS2C)
	err := grpc.Invoke(ctx, "/proto.CaptchaManager/GetCaptcha", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captchaManagerClient) CheckCaptcha(ctx context.Context, in *CheckCaptchaC2S, opts ...grpc.CallOption) (*CheckCaptchaS2C, error) {
	out := new(CheckCaptchaS2C)
	err := grpc.Invoke(ctx, "/proto.CaptchaManager/CheckCaptcha", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CaptchaManager service

type CaptchaManagerServer interface {
	GetCaptcha(context.Context, *GetCaptchaC2S) (*GetCaptchaS2C, error)
	CheckCaptcha(context.Context, *CheckCaptchaC2S) (*CheckCaptchaS2C, error)
}

func RegisterCaptchaManagerServer(s *grpc.Server, srv CaptchaManagerServer) {
	s.RegisterService(&_CaptchaManager_serviceDesc, srv)
}

func _CaptchaManager_GetCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptchaC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaManagerServer).GetCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CaptchaManager/GetCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaManagerServer).GetCaptcha(ctx, req.(*GetCaptchaC2S))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptchaManager_CheckCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCaptchaC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptchaManagerServer).CheckCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CaptchaManager/CheckCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptchaManagerServer).CheckCaptcha(ctx, req.(*CheckCaptchaC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _CaptchaManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CaptchaManager",
	HandlerType: (*CaptchaManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCaptcha",
			Handler:    _CaptchaManager_GetCaptcha_Handler,
		},
		{
			MethodName: "CheckCaptcha",
			Handler:    _CaptchaManager_CheckCaptcha_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for Register service

type RegisterClient interface {
	Register(ctx context.Context, in *RegisterC2S, opts ...grpc.CallOption) (*RegisterS2C, error)
	GetRegCaptcha(ctx context.Context, in *RegCaptchaC2S, opts ...grpc.CallOption) (*RegCaptchaS2C, error)
}

type registerClient struct {
	cc *grpc.ClientConn
}

func NewRegisterClient(cc *grpc.ClientConn) RegisterClient {
	return &registerClient{cc}
}

func (c *registerClient) Register(ctx context.Context, in *RegisterC2S, opts ...grpc.CallOption) (*RegisterS2C, error) {
	out := new(RegisterS2C)
	err := grpc.Invoke(ctx, "/proto.Register/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registerClient) GetRegCaptcha(ctx context.Context, in *RegCaptchaC2S, opts ...grpc.CallOption) (*RegCaptchaS2C, error) {
	out := new(RegCaptchaS2C)
	err := grpc.Invoke(ctx, "/proto.Register/GetRegCaptcha", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Register service

type RegisterServer interface {
	Register(context.Context, *RegisterC2S) (*RegisterS2C, error)
	GetRegCaptcha(context.Context, *RegCaptchaC2S) (*RegCaptchaS2C, error)
}

func RegisterRegisterServer(s *grpc.Server, srv RegisterServer) {
	s.RegisterService(&_Register_serviceDesc, srv)
}

func _Register_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Register/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).Register(ctx, req.(*RegisterC2S))
	}
	return interceptor(ctx, in, info, handler)
}

func _Register_GetRegCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegCaptchaC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterServer).GetRegCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Register/GetRegCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterServer).GetRegCaptcha(ctx, req.(*RegCaptchaC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _Register_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Register",
	HandlerType: (*RegisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Register_Register_Handler,
		},
		{
			MethodName: "GetRegCaptcha",
			Handler:    _Register_GetRegCaptcha_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for PasswordManager service

type PasswordManagerClient interface {
	GetPasswordCaptcha(ctx context.Context, in *PasswordCaptchaC2S, opts ...grpc.CallOption) (*PasswordCaptchaS2C, error)
	ChangePassword(ctx context.Context, in *ChangePasswordC2S, opts ...grpc.CallOption) (*ChangePasswordS2C, error)
}

type passwordManagerClient struct {
	cc *grpc.ClientConn
}

func NewPasswordManagerClient(cc *grpc.ClientConn) PasswordManagerClient {
	return &passwordManagerClient{cc}
}

func (c *passwordManagerClient) GetPasswordCaptcha(ctx context.Context, in *PasswordCaptchaC2S, opts ...grpc.CallOption) (*PasswordCaptchaS2C, error) {
	out := new(PasswordCaptchaS2C)
	err := grpc.Invoke(ctx, "/proto.PasswordManager/GetPasswordCaptcha", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordManagerClient) ChangePassword(ctx context.Context, in *ChangePasswordC2S, opts ...grpc.CallOption) (*ChangePasswordS2C, error) {
	out := new(ChangePasswordS2C)
	err := grpc.Invoke(ctx, "/proto.PasswordManager/ChangePassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PasswordManager service

type PasswordManagerServer interface {
	GetPasswordCaptcha(context.Context, *PasswordCaptchaC2S) (*PasswordCaptchaS2C, error)
	ChangePassword(context.Context, *ChangePasswordC2S) (*ChangePasswordS2C, error)
}

func RegisterPasswordManagerServer(s *grpc.Server, srv PasswordManagerServer) {
	s.RegisterService(&_PasswordManager_serviceDesc, srv)
}

func _PasswordManager_GetPasswordCaptcha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordCaptchaC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).GetPasswordCaptcha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PasswordManager/GetPasswordCaptcha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).GetPasswordCaptcha(ctx, req.(*PasswordCaptchaC2S))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordManager_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordManagerServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PasswordManager/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordManagerServer).ChangePassword(ctx, req.(*ChangePasswordC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _PasswordManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PasswordManager",
	HandlerType: (*PasswordManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPasswordCaptcha",
			Handler:    _PasswordManager_GetPasswordCaptcha_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _PasswordManager_ChangePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for Login service

type LoginClient interface {
	Login(ctx context.Context, in *LoginC2S, opts ...grpc.CallOption) (*LoginS2C, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Login(ctx context.Context, in *LoginC2S, opts ...grpc.CallOption) (*LoginS2C, error) {
	out := new(LoginS2C)
	err := grpc.Invoke(ctx, "/proto.Login/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Login service

type LoginServer interface {
	Login(context.Context, *LoginC2S) (*LoginS2C, error)
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Login/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Login(ctx, req.(*LoginC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Login_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for UserInfoManager service

type UserInfoManagerClient interface {
	UserInfoModify(ctx context.Context, in *UserInfoModifyC2S, opts ...grpc.CallOption) (*UserInfoModifyS2C, error)
	UserInfoGet(ctx context.Context, in *UserInfoGetC2S, opts ...grpc.CallOption) (*UserInfoGetS2C, error)
}

type userInfoManagerClient struct {
	cc *grpc.ClientConn
}

func NewUserInfoManagerClient(cc *grpc.ClientConn) UserInfoManagerClient {
	return &userInfoManagerClient{cc}
}

func (c *userInfoManagerClient) UserInfoModify(ctx context.Context, in *UserInfoModifyC2S, opts ...grpc.CallOption) (*UserInfoModifyS2C, error) {
	out := new(UserInfoModifyS2C)
	err := grpc.Invoke(ctx, "/proto.UserInfoManager/UserInfoModify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoManagerClient) UserInfoGet(ctx context.Context, in *UserInfoGetC2S, opts ...grpc.CallOption) (*UserInfoGetS2C, error) {
	out := new(UserInfoGetS2C)
	err := grpc.Invoke(ctx, "/proto.UserInfoManager/UserInfoGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserInfoManager service

type UserInfoManagerServer interface {
	UserInfoModify(context.Context, *UserInfoModifyC2S) (*UserInfoModifyS2C, error)
	UserInfoGet(context.Context, *UserInfoGetC2S) (*UserInfoGetS2C, error)
}

func RegisterUserInfoManagerServer(s *grpc.Server, srv UserInfoManagerServer) {
	s.RegisterService(&_UserInfoManager_serviceDesc, srv)
}

func _UserInfoManager_UserInfoModify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoModifyC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoManagerServer).UserInfoModify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserInfoManager/UserInfoModify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoManagerServer).UserInfoModify(ctx, req.(*UserInfoModifyC2S))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInfoManager_UserInfoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoGetC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserInfoManagerServer).UserInfoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserInfoManager/UserInfoGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserInfoManagerServer).UserInfoGet(ctx, req.(*UserInfoGetC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserInfoManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserInfoManager",
	HandlerType: (*UserInfoManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfoModify",
			Handler:    _UserInfoManager_UserInfoModify_Handler,
		},
		{
			MethodName: "UserInfoGet",
			Handler:    _UserInfoManager_UserInfoGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for GeoManager service

type GeoManagerClient interface {
	UserGeoUpload(ctx context.Context, in *GeoUploadC2S, opts ...grpc.CallOption) (*CommonS2C, error)
}

type geoManagerClient struct {
	cc *grpc.ClientConn
}

func NewGeoManagerClient(cc *grpc.ClientConn) GeoManagerClient {
	return &geoManagerClient{cc}
}

func (c *geoManagerClient) UserGeoUpload(ctx context.Context, in *GeoUploadC2S, opts ...grpc.CallOption) (*CommonS2C, error) {
	out := new(CommonS2C)
	err := grpc.Invoke(ctx, "/proto.GeoManager/UserGeoUpload", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GeoManager service

type GeoManagerServer interface {
	UserGeoUpload(context.Context, *GeoUploadC2S) (*CommonS2C, error)
}

func RegisterGeoManagerServer(s *grpc.Server, srv GeoManagerServer) {
	s.RegisterService(&_GeoManager_serviceDesc, srv)
}

func _GeoManager_UserGeoUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoUploadC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoManagerServer).UserGeoUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GeoManager/UserGeoUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoManagerServer).UserGeoUpload(ctx, req.(*GeoUploadC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeoManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GeoManager",
	HandlerType: (*GeoManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserGeoUpload",
			Handler:    _GeoManager_UserGeoUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for SessionManager service

type SessionManagerClient interface {
	GetSession(ctx context.Context, in *GetSessionC2S, opts ...grpc.CallOption) (*GetSessionS2C, error)
	AuthSession(ctx context.Context, in *AuthC2S, opts ...grpc.CallOption) (*CommonS2C, error)
}

type sessionManagerClient struct {
	cc *grpc.ClientConn
}

func NewSessionManagerClient(cc *grpc.ClientConn) SessionManagerClient {
	return &sessionManagerClient{cc}
}

func (c *sessionManagerClient) GetSession(ctx context.Context, in *GetSessionC2S, opts ...grpc.CallOption) (*GetSessionS2C, error) {
	out := new(GetSessionS2C)
	err := grpc.Invoke(ctx, "/proto.SessionManager/GetSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) AuthSession(ctx context.Context, in *AuthC2S, opts ...grpc.CallOption) (*CommonS2C, error) {
	out := new(CommonS2C)
	err := grpc.Invoke(ctx, "/proto.SessionManager/AuthSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SessionManager service

type SessionManagerServer interface {
	GetSession(context.Context, *GetSessionC2S) (*GetSessionS2C, error)
	AuthSession(context.Context, *AuthC2S) (*CommonS2C, error)
}

func RegisterSessionManagerServer(s *grpc.Server, srv SessionManagerServer) {
	s.RegisterService(&_SessionManager_serviceDesc, srv)
}

func _SessionManager_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionManager/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).GetSession(ctx, req.(*GetSessionC2S))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_AuthSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).AuthSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SessionManager/AuthSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).AuthSession(ctx, req.(*AuthC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SessionManager",
	HandlerType: (*SessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSession",
			Handler:    _SessionManager_GetSession_Handler,
		},
		{
			MethodName: "AuthSession",
			Handler:    _SessionManager_AuthSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

// Client API for Relation service

type RelationClient interface {
	RecentContactGet(ctx context.Context, in *RecentContactGetC2S, opts ...grpc.CallOption) (*RecentContactGetS2C, error)
}

type relationClient struct {
	cc *grpc.ClientConn
}

func NewRelationClient(cc *grpc.ClientConn) RelationClient {
	return &relationClient{cc}
}

func (c *relationClient) RecentContactGet(ctx context.Context, in *RecentContactGetC2S, opts ...grpc.CallOption) (*RecentContactGetS2C, error) {
	out := new(RecentContactGetS2C)
	err := grpc.Invoke(ctx, "/proto.Relation/RecentContactGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Relation service

type RelationServer interface {
	RecentContactGet(context.Context, *RecentContactGetC2S) (*RecentContactGetS2C, error)
}

func RegisterRelationServer(s *grpc.Server, srv RelationServer) {
	s.RegisterService(&_Relation_serviceDesc, srv)
}

func _Relation_RecentContactGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentContactGetC2S)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationServer).RecentContactGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Relation/RecentContactGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationServer).RecentContactGet(ctx, req.(*RecentContactGetC2S))
	}
	return interceptor(ctx, in, info, handler)
}

var _Relation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Relation",
	HandlerType: (*RelationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecentContactGet",
			Handler:    _Relation_RecentContactGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto1.RegisterFile("rpc.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0x3d, 0xf4, 0x8f, 0x4e, 0x5f, 0x59, 0x5f, 0xd0, 0x1e, 0xbd, 0x0a, 0x05, 0x63,
	0x0f, 0x22, 0x08, 0x4a, 0xa0, 0x22, 0x54, 0x90, 0x96, 0x82, 0xd7, 0x35, 0xdd, 0x26, 0xc1, 0x76,
	0x37, 0x24, 0x2b, 0xe2, 0xc9, 0x6f, 0xe0, 0xd9, 0x6f, 0xe0, 0xd7, 0x74, 0x27, 0xbb, 0x93, 0x26,
	0xb1, 0x3d, 0x75, 0xfb, 0x9b, 0x99, 0x87, 0x67, 0x86, 0x27, 0xb0, 0x9f, 0x26, 0xc1, 0x30, 0x49,
	0x95, 0x56, 0xac, 0x99, 0xff, 0x0c, 0xda, 0xc1, 0x2a, 0x16, 0x52, 0x5b, 0xe8, 0x7d, 0x35, 0xa0,
	0xeb, 0xf3, 0x44, 0x07, 0x11, 0x7f, 0xe4, 0x92, 0x87, 0x22, 0x65, 0xd7, 0x00, 0xf7, 0x42, 0x3b,
	0xc8, 0x0e, 0x6d, 0xe3, 0x70, 0x83, 0x7c, 0x6f, 0x36, 0xf8, 0x4b, 0x67, 0x9e, 0x7f, 0xf6, 0x8f,
	0xdd, 0x42, 0xdb, 0x8f, 0x44, 0xf0, 0x4a, 0xd3, 0xc7, 0xae, 0xaf, 0x0c, 0x71, 0x7e, 0x1b, 0xcf,
	0x15, 0xbc, 0x4f, 0xd8, 0x9b, 0x8a, 0x30, 0xce, 0xb4, 0x71, 0x32, 0x2a, 0xbd, 0x99, 0x9b, 0x20,
	0x80, 0x2a, 0x75, 0x66, 0x3d, 0xdc, 0x40, 0xc7, 0xd8, 0x32, 0xac, 0xbe, 0xc2, 0x06, 0x95, 0x57,
	0xd8, 0x50, 0x6b, 0xe0, 0xa7, 0x01, 0xbd, 0x27, 0x9e, 0x65, 0xef, 0x2a, 0x5d, 0xd0, 0x49, 0x26,
	0xc0, 0x8c, 0x24, 0x51, 0xd2, 0x3d, 0x75, 0x0a, 0x35, 0x8e, 0xe2, 0x3b, 0x4a, 0xd6, 0xe0, 0xd8,
	0x9c, 0x3c, 0xe2, 0x32, 0x14, 0x54, 0x65, 0x27, 0xc5, 0x39, 0xca, 0x18, 0x85, 0xb6, 0x57, 0xac,
	0xd3, 0x11, 0x34, 0x27, 0x2a, 0x8c, 0x25, 0x3b, 0xa7, 0x47, 0xcf, 0x75, 0xe7, 0xff, 0x70, 0xbc,
	0x02, 0xec, 0xd4, 0xb7, 0xd9, 0x6f, 0x9e, 0x89, 0xf4, 0x41, 0x2e, 0x15, 0xed, 0x67, 0x1c, 0x15,
	0x48, 0x2d, 0xe2, 0xe5, 0x47, 0xe1, 0xa8, 0x8a, 0xcb, 0x8e, 0xaa, 0x15, 0x3a, 0x7d, 0x8b, 0xb0,
	0xb9, 0x17, 0x3b, 0xaa, 0xb5, 0x62, 0x5a, 0x8c, 0xc2, 0x16, 0x6c, 0xad, 0x8d, 0x31, 0x79, 0x85,
	0xa9, 0x2b, 0xe8, 0x60, 0x87, 0x21, 0xf3, 0x64, 0xa5, 0xf8, 0x82, 0x1d, 0x14, 0xa1, 0x73, 0x04,
	0xc5, 0xfa, 0x74, 0x20, 0xb5, 0x5e, 0x2b, 0x49, 0x19, 0xea, 0xce, 0x44, 0x96, 0xc5, 0x4a, 0x56,
	0x33, 0xed, 0x60, 0x39, 0xd3, 0x0e, 0xd5, 0x32, 0xed, 0xa8, 0x5d, 0xea, 0x02, 0x5a, 0x77, 0x6f,
	0x3a, 0xa2, 0xe1, 0xae, 0x6b, 0x43, 0xb6, 0xcb, 0xc0, 0x33, 0x06, 0x77, 0xc5, 0x35, 0xf6, 0x4f,
	0xa0, 0x3f, 0x15, 0x81, 0xf9, 0xe2, 0x7c, 0x25, 0x35, 0x0f, 0x34, 0x1e, 0x66, 0x50, 0x64, 0xaf,
	0x5a, 0x40, 0xbd, 0x5d, 0xb5, 0x5c, 0xf9, 0xe5, 0x7f, 0x5e, 0xbc, 0xfc, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x71, 0xd2, 0x5d, 0x73, 0xd8, 0x03, 0x00, 0x00,
}
