// Code generated by protoc-gen-go.
// source: server.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AuthReq struct {
	UserId  uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Session string `protobuf:"bytes,2,opt,name=session" json:"session,omitempty"`
}

func (m *AuthReq) Reset()                    { *m = AuthReq{} }
func (m *AuthReq) String() string            { return proto1.CompactTextString(m) }
func (*AuthReq) ProtoMessage()               {}
func (*AuthReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type GetSessionReq struct {
	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *GetSessionReq) Reset()                    { *m = GetSessionReq{} }
func (m *GetSessionReq) String() string            { return proto1.CompactTextString(m) }
func (*GetSessionReq) ProtoMessage()               {}
func (*GetSessionReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type GetSessionRes struct {
	ErrCode uint32 `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	UserId  uint64 `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Session string `protobuf:"bytes,3,opt,name=session" json:"session,omitempty"`
}

func (m *GetSessionRes) Reset()                    { *m = GetSessionRes{} }
func (m *GetSessionRes) String() string            { return proto1.CompactTextString(m) }
func (*GetSessionRes) ProtoMessage()               {}
func (*GetSessionRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func init() {
	proto1.RegisterType((*AuthReq)(nil), "proto.AuthReq")
	proto1.RegisterType((*GetSessionReq)(nil), "proto.GetSessionReq")
	proto1.RegisterType((*GetSessionRes)(nil), "proto.GetSessionRes")
}

func init() { proto1.RegisterFile("server.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x36, 0x5c, 0xec,
	0x8e, 0xa5, 0x25, 0x19, 0x41, 0xa9, 0x85, 0x42, 0xe2, 0x5c, 0xec, 0xa5, 0x40, 0x25, 0xf1, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x04, 0x17,
	0x7b, 0x71, 0x6a, 0x71, 0x71, 0x66, 0x7e, 0x9e, 0x04, 0x13, 0x50, 0x82, 0x33, 0x08, 0xc6, 0x55,
	0xd2, 0xe0, 0xe2, 0x75, 0x4f, 0x2d, 0x09, 0x86, 0xf0, 0xf0, 0x99, 0xa1, 0x14, 0x8b, 0xaa, 0xb2,
	0x58, 0x48, 0x92, 0x8b, 0x23, 0xb5, 0xa8, 0x28, 0x3e, 0x39, 0x3f, 0x25, 0x15, 0xac, 0x94, 0x37,
	0x88, 0x1d, 0xc8, 0x77, 0x06, 0x72, 0x91, 0x0d, 0x61, 0xc2, 0xe5, 0x10, 0x66, 0x14, 0x87, 0x24,
	0xb1, 0x81, 0x7d, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x63, 0x12, 0x7e, 0x61, 0xe4, 0x00,
	0x00, 0x00,
}
